name: Run Tests
run-name: Testing Pipeline
on: [push]
jobs:
  Testing-Pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: ./environment.yml
          activate-environment: Intro2GithubActions
          auto-activate-base: false
      - run: pytest
      - run: echo "ğŸ This job's status is ${{ job.status }}."
