name: Run Tests
run-name: Testing Pipeline
on: [push]
jobs:
  Testing-Pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
        name: checkout repo
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: ./environment.yml
          activate-environment: Intro2GithubActions
          auto-activate-base: false
      - run: echo $(which python)
      - run: pytest -v
      - run: echo "üçè This job's status is ${{ job.status }}."

  get-num-square:
    runs-on: ubuntu-latest
    name: Return's the number square
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch num squared
        id: get_square
        uses: ./ # Uses an action in the root directory
        # or use a released Github Action
        # uses: shipyard/github-action/fetch-shipyard-env@1.0.0
        with:
          num: 12
      - name: Print the square
        run: echo "${{ steps.get_square.outputs.num_squared }}"
