name: uv tag demo
on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, labeled, unlabeled]

jobs:

  Try-uv-Tag:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "The job was triggered by a ${{ github.event_name }} event."

      - run: echo "The job is running on a ${{ runner.os }} server"

      - run: echo "The name of your branch is ${{ github.ref }} and your repo is ${{ github.repository }}."

      - name: Check out Repo Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - run: echo "the ${{ github.repository }} repo has been cloned to the runner."

      - name: List files in the repo
        run: |
          ls ${{ github.workspace }}

      - run: echo "this jobs status is ${{ job.status }}."

      - name: checking my action
        id: foo
        uses: eytanohana/uv-release-tools@bd55fa425a5eb0a63f7032e09d3ca6849535b0d9
        with:
          mode: "validate"
      - name: check outputs
        run: |
          echo "is_valid: ${{ steps.foo.outputs.valid }} , release type: ${{ steps.foo.outputs.release_type }} "


